[package]
name = "forgotten-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
forgotten-core = { path = "../forgotten-core" }
forgotten-persistence = { path = "../forgotten-persistence" }
forgotten-protocol = { path = "../forgotten-protocol" }

[lints]
workspace = true
