[package]
name = "forgotten-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
forgotten-core = { path = "../forgotten-core" }
forgotten-config = { path = "../forgotten-config" }
forgotten-persistence = { path = "../forgotten-persistence" }
forgotten-protocol = { path = "../forgotten-protocol" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lints]
workspace = true
