[package]
name = "forgotten-persistence"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
argon2 = "0.5"
forgotten-core = { path = "../forgotten-core" }
rand = "0.8"
rusqlite = { version = "0.31", features = ["bundled"] }

[lints]
workspace = true
